version: '3.8'

services:
  arbitrage-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sui-arbitrage-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Mount logs directory to persist logs
      - ./logs:/app/logs
    environment:
      # Override any env vars here if needed
      - NODE_ENV=production
    # Resource limits for safety
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - sui-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  sui-network:
    driver: bridge
